### ISSUE TITLE
Clarify the version of JSONPath that's being used

### ISSUE THREAD

**Issue by lornajane** [OAI/Overlay-Specification#49]
We don't specify a version of JSONPath, and we should.

**Comment by ralfhandl** [comment]
For the [ReSpec rendering](https://ralfhandl.github.io/OpenAPI-Specification/overlay/v1.0.0.html#overlay-document) I chose 

> **[RFC9535]**
> [JSONPath: Query Expressions for JSON](https://www.rfc-editor.org/rfc/rfc9535). S. Gössner, Ed.; G. Normington, Ed.; C. Bormann, Ed.. IETF. February 2024. Proposed Standard. URL: https://www.rfc-editor.org/rfc/rfc9535

**Comment by lornajane** [comment]
Do we need to do more on this?

**Comment by ralfhandl** [comment]
I don't think so.

**Comment by dret** [comment]
Just asking: Is that clear enough that implementations for sure will use RFC 9535 as their default syntax? That's pretty important for interoperability, and different people still seems to think of different things when they say JSONPath. Just being pedantic here because it took me longer than it should have to figure out that when Spectral says JSONPath, they don't refer to the RFC and refer to some rather implementation-specific prior version of it.

**Comment by handrews** [comment]
@dret the 1.0.0 spec normatively cites RFC9535, so it's definitely _technically_ clear.  However it should probably be more prominent, and a note on the current highly variable state of implementations would not be amiss.
